#
# EcoSkills
# by Auxilor
#

gui:
  rows: 6

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111101111"
      - "111111111"
      - "110000011"
      - "110010011"
      - "111111111"
      - "111101111"

  player-info:
    row: 1
    column: 5

    name: "&f%player%'s &fStats:"
    lore:
      - "&f"
      - " %ecoskills_defense_name%&f %ecoskills_defense%"
      - " %ecoskills_strength_name%&f %ecoskills_strength%"
      - " %ecoskills_crit_chance_name%&f %ecoskills_crit_chance%"
      - " %ecoskills_crit_damage_name%&f %ecoskills_crit_damage%"
      - " %ecoskills_speed_name%&f %ecoskills_speed%"
      - " %ecoskills_wisdom_name%&f %ecoskills_wisdom%"

  close:
    material: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

  skill-icon:
    name: "&#ff00ae%skill% &d%level_numeral%"
    lore:
      - "&8&o%description%"
      - "&f"
      - "%skill_specific%"
      - "&f"
      - "&fProgress to next level:"
      - "&8» &e%percentage_progress%"
      - "&8» &e%current_xp%&8/&7%required_xp% &fXP"
      - "&f"
      - "&eClick to view Level Progression!"

skills:
  # Add more levels depending on the highest max level for all skills
  level-xp-requirements:
    - 50
    - 125
    - 200
    - 300
    - 500
    - 750
    - 1000
    - 1500
    - 2000
    - 3500
    - 5000
    - 7500
    - 10000
    - 15000
    - 20000
    - 30000
    - 50000
    - 75000
    - 100000
    - 200000
    - 300000
    - 400000
    - 500000
    - 600000
    - 700000
    - 800000
    - 900000
    - 1000000
    - 1100000
    - 1200000
    - 1300000
    - 1400000
    - 1500000
    - 1600000
    - 1700000
    - 1800000
    - 1900000
    - 2000000
    - 2100000
    - 2200000
    - 2300000
    - 2400000
    - 2500000
    - 2600000
    - 2750000
    - 2900000
    - 3100000
    - 3400000
    - 3700000
    - 4000000

  # Ways to tell the player about skill progress
  progress:
    action-bar:
      # If the action bar should be used
      enabled: true
      # The actionbar message that should be sent
      format: "&f%skill% &8| &9(%current_xp%/%required_xp%) &e+%gained_xp%"
    sound:
      # If a sound should be played
      enabled: true
      # The sound that should be played
      id: entity_experience_orb_pickup
      # Pitch between 0.5 and 2
      pitch: 2
      # The volume
      volume: 0.1


  # Ways to tell the player about levelling up
  level-up:
    message:
      level-as-numeral: true
      enabled: true
      message:
        - "&f"
        - " &#ff00aeYou levelled up &d%skill%&#ff00ae to &eLevel %level%&#ff00ae!"
        - "&f"
        - " &#ff00ae&lREWARDS:"
        - "%rewards%"
        - "&f"
    sound:
      # If a sound should be played
      enabled: true
      # The sound that should be played
      id: entity_player_levelup
      # Pitch between 0.5 and 2
      pitch: 0.8

  mining:
    gui-item: stone_pickaxe
    gui-position:
      row: 3
      column: 3
    gui-lore:
      - "&fImproves Stats:"
      - "&8» &r%ecoskills_defense_name%"
      - "&f"
      - "&fEffects:"
      - "&8» &r&6Versatile Tools %ecoskills_versatile_tools_numeral%"

    # The maximum obtainable level
    max-level: 50

    # The level/skill increases to give on levelup
    level-up-rewards:
      - "defense:2"
      - "versatile_tools:1"

    rewards-messages:
      - " &8» &r&f+1 %ecoskills_defense_name%"
      - " &8» &r&6Versatile Tools %ecoskills_versatile_tools_numeral%"

    # The xp rewards for each block type
    # Specify with type:xp
    xp-rewards:
      - "stone:1"
      - "diorite:1"
      - "andesite:1"
      - "granite:1"
      - "tuff:1"
      - "deepslate:1"
      - "cobblestone:1"
      - "netherrack:0.5"
      - "sand:3"
      - "gravel:4"
      - "nether_quartz_ore:5"
      - "end_stone:3"
      - "coal_ore:5"
      - "deepslate_coal_ore:5"
      - "iron_ore:5"
      - "deepslate_iron_ore:5"
      - "gold_ore:6"
      - "deepslate_gold_ore:6"
      - "lapis_lazuli_ore:7"
      - "deepslate_lapis_lazuli_ore:7"
      - "redstone_ore:7"
      - "deepslate_redstone_ore:7"
      - "emerald_ore:9"
      - "deepslate_emerald_ore:9"
      - "diamond_ore:10"
      - "deepslate_diamond_ore:10"
      - "ancient_debris:20"
  combat:
    gui-item: stone_sword
    gui-position:
      row: 3
      column: 4
    gui-lore:
      - "&fImproves Stats:"
      - "&8» &r%ecoskills_strength_name%"
      - "&8» &r%ecoskills_crit_damage_name%"
      - "&f"
      - "&fEffects:"
      - "&8» &r&6Serrated Strikes %ecoskills_serrated_strikes_numeral%"

    # The maximum obtainable level
    max-level: 50

    # The experience to give for each hp of a killed enemy
    xp-per-heart: 0.33

    # The level/skill increases to give on levelup
    level-up-rewards:
      - "strength:2"
      - "crit_damage:1"
      - "serrated_strikes:1"

    rewards-messages:
      - " &8» &r&f+2 %ecoskills_strength_name%"
      - " &8» &r&f+1 %ecoskills_crit_damage_name%"
      - " &8» &r&6Serrated Strikes %ecoskills_serrated_strikes_numeral%"
  enchanting:
    gui-item: enchanting_table
    gui-position:
      row: 3
      column: 5
    gui-lore:
      - "&fImproves Stats:"
      - "&8» &r%ecoskills_wisdom_name%"
      - "&8» &r%ecoskills_crit_chance_name%"
      - "&f"
      - "&fEffects:"
      - "&8» &r&6Second Chance %ecoskills_second_chance_numeral%"

    # The maximum obtainable level
    max-level: 50

    # The experience to give for each level cost of enchanting
    xp-per-level: 4

    # The level/skill increases to give on levelup
    level-up-rewards:
      - "wisdom:2"
      - "crit_chance:1"
      - "second_chance:1"

    rewards-messages:
      - " &8» &r&f+2 %ecoskills_wisdom_name%"
      - " &8» &r&f+1 %ecoskills_crit_chance_name%"
      - " &8» &r&6Second Chance %ecoskills_second_chance_numeral%"
  farming:
    gui-position:
      row: 3
      column: 6
    gui-lore:
      - "&fImproves Stats:"
      - "&8» &r%ecoskills_crit_damage_name%"
      - "&8» &r%ecoskills_wisdom_name%"
      - "&f"
      - "&fEffects:"
      - "&8» &r&6Bountiful Harvest %ecoskills_bountiful_harvest_numeral%"

    gui-item: golden_hoe
    # The maximum obtainable level
    max-level: 50

    # The level/skill increases to give on levelup
    level-up-rewards:
      - "crit_damage:2"
      - "wisdom:1"
      - "bountiful_harvest:1"

    rewards-messages:
      - " &8» &r&f+2 %ecoskills_crit_damage_name%"
      - " &8» &r&f+1 %ecoskills_wisdom_name%"
      - " &8» &r&6Bountiful Harvest %ecoskills_bountiful_harvest_numeral%"

    # The xp rewards for each crop type
    # Specify with type:xp
    xp-rewards:
      - "wheat:4"
      - "potato:4"
      - "carrots:4"
      - "melon:4"
      - "pumpkin:4.5"
      - "cactus:2"
      - "sugar_cane:2"
      - "brown_mushroom:6"
      - "red_mushroom:6"
      - "cocoa_beans:3"
  woodcutting:
    gui-position:
      row: 3
      column: 7
    gui-item: jungle_sapling
    gui-lore:
      - "&fImproves Stats:"
      - "&8» &r%ecoskills_strength_name%"
      - "&f"
      - "&fEffects:"
      - "&8» &r&6Craftsmanship %ecoskills_craftsmanship_numeral%"

    # The maximum obtainable level
    max-level: 50

    # The level/skill increases to give on levelup
    level-up-rewards:
      - "strength:2"
      - "craftsmanship:1"

    rewards-messages:
      - " &8» &r&f+2 %ecoskills_strength_name%"
      - " &8» &r&6Craftsmanship %ecoskills_craftsmanship_numeral%"

    # The xp rewards for each crop type
    # Specify with type:xp
    xp-rewards:
      - "oak_log:6"
      - "birch_log:6"
      - "spruce_log:6"
      - "jungle_log:6"
      - "acacia_log:6"
      - "dark_oak_log:6"
      - "crimson_stem:14"
      - "warped_stem:14"
  fishing:
    gui-position:
      row: 4
      column: 3
    gui-lore:
      - "&fImproves Stats:"
      - "&8» &r%ecoskills_defense_name%"
      - "&8» &r%ecoskills_wisdom_name%"
      - "&f"
      - "&fEffects:"
      - "&8» &r&6Eye of the Depths %ecoskills_eye_of_the_depths_numeral%"

    gui-item: fishing_rod
    # The maximum obtainable level
    max-level: 50

    # The experience to give for each in-game experience dropped
    xp-per-experience-dropped: 3.5

    # The level/skill increases to give on levelup
    level-up-rewards:
      - "defense:2"
      - "wisdom:1"
      - "eye_of_the_depths:1"

    rewards-messages:
      - " &8» &r&f+2 %ecoskills_defense_name%"
      - " &8» &r&f+1 %ecoskills_wisdom_name%"
      - " &8» &r&6Eye of the Depths %ecoskills_eye_of_the_depths_numeral%"
  alchemy:
    gui-position:
      row: 4
      column: 4
    gui-lore:
      - "&fImproves Stats:"
      - "&8» &r%ecoskills_crit_chance_name%"
      - "&8» &r%ecoskills_wisdom_name%"
      - "&f"
      - "&fEffects:"
      - "&8» &r&6Potionmaster %ecoskills_potionmaster_numeral%"

    gui-item: brewing_stand
    # The maximum obtainable level
    max-level: 50

    # The level/skill increases to give on levelup
    level-up-rewards:
      - "crit_chance:2"
      - "wisdom:1"
      - "potionmaster:1"

    rewards-messages:
      - " &8» &r&f+2 %ecoskills_crit_chance_name%"
      - " &8» &r&f+1 %ecoskills_wisdom_name%"
      - " &8» &r&6Potionmaster %ecoskills_potionmaster_numeral%"

    # The experience to give for each brewing ingredient
    xp-rewards:
      - "nether_wart:6"
      - "redstone:6"
      - "glowstone_dust:6"
      - "fermented_spider_eye:6"
      - "gunpowder:6"
      - "dragon_breath:42"
      - "sugar:14"
      - "rabbit_foot:22"
      - "glistering_melon_slice:22"
      - "spider_eye:8"
      - "pufferfish:14"
      - "magma_cream:12"
      - "golden_carrot:22"
      - "blaze_powder:12"
      - "ghast_tear:12"
      - "turtle_shell:80"
      - "phantom_membrane:34"
  armory:
    gui-position:
      row: 4
      column: 6
    gui-lore:
      - "&fImproves Stats:"
      - "&8» &r%ecoskills_defense_name%"
      - "&8» &r%ecoskills_speed_name%"
      - "&f"
      - "&fEffects:"
      - "&8» &r&6Shamanism %ecoskills_shamanism_numeral%"

    gui-item: iron_chestplate
    # The maximum obtainable level
    max-level: 50

    # The experience to give for each hp of damage taken
    xp-per-hp: 0.72

    # The level/skill increases to give on levelup
    level-up-rewards:
      - "defense:2"
      - "speed:1"
      - "shamanism:1"

    rewards-messages:
      - " &8» &r&f+2 %ecoskills_defense_name%"
      - " &8» &r&f+1 %ecoskills_speed_name%"
      - " &8» &r&6Shamanism %ecoskills_shamanism_numeral%"
  exploration:
    gui-position:
      row: 4
      column: 7
    gui-lore:
      - "&fImproves Stats:"
      - "&8» &r%ecoskills_speed_name%"
      - "&f"
      - "&fEffects:"
      - "&8» &r&6Seamless Movement %ecoskills_seamless_movement_numeral%"

    gui-item: leather_boots
    # The maximum obtainable level
    max-level: 50

    # The level/skill increases to give on levelup
    level-up-rewards:
      - "speed:2"
      - "seamless_movement:1"

    rewards-messages:
      - " &8» &r&f+2 %ecoskills_speed_name%"
      - " &8» &r&6Seamless Movement %ecoskills_seamless_movement_numeral%"

    # Chance to give 1 xp every time the player moves
    xp-on-move-chance: 0.05
    # The amount of xp to give before any modifiers are applied
    base-xp-to-give: 20
    # If the amount of xp given should be higher when travelling faster
    multiply-xp-by-speed: true

    # The amount of experience to give for each point of fall damage taken
    fall-damage-xp-per-hp: 16

stats:
  defense:
    # 100% halves the incoming damage
    percent-less-damage-per-level: 1
  strength:
    # 100% is double damage
    percent-more-damage-per-level: 1
  crit_chance:
    # Nothing happens above 100%, 200% is the same as it.
    chance-per-level: 1
  crit_damage:
    # The percent more damage to deal on crits for each level.
    percent-more-damage-per-level: 2
    # The amount more damage to deal on crits by default.
    base-percent-more: 50
  speed:
    # The percent more speed to give for the speed attribute (internal in the game)
    # for each level
    percent-faster-per-level: 1
  wisdom:
    # The percent more xp to gain from orbs for each level of the stat.
    percent-more-xp-gain: 1

effects:
  bountiful_harvest:
    # Chance is as a percentage; if the chance for a player is over 100 then it will always be double drops
    # with a chance to get triple drops. Same goes if above 200, but then it will always be triple with a chance
    # for quadruple.
    chance-per-level: 1
  versatile_tools:
    # The percent (%) more damage to deal with a pickaxe for each level of the effect.
    percent-more-per-level: 2
  eye_of_the_depths:
    # Chance is as a percentage.
    chance-per-level: 0.1
    # The rare loot items are listed below.
    # You can import drops from the following plugins:
    # EcoArmor, EcoItems, Talismans, StatTrackers, EcoWeapons, Reforges, Oraxen
    # You can also use vanilla items with their material
    # You can set enchantments on items with the following syntax:
    # <item> <enchantment:level> <enchantment:level> etc
    # For example, a reaper scythe with Razor 4 and Criticals 3 would be:
    # ecoweapons:reaper_scythe razor:4 criticals:3
    rare-loot-items:
      - enchanted_book confusion:1
      - enchanted_book confusion:2
      - netherite_ingot
      - ecoarmor:set_miner_helmet
      - ecoarmor:set_miner_chestplate
      - ecoarmor:set_miner_leggings
      - ecoarmor:set_miner_boots
      - reforges:dynamic
  serrated_strikes:
    # Chance is as a percentage.
    chance-per-level: 2
    # The damage to deal for each 'bleed tick'
    bleed-tick-damage: 2
    # The amount of ticks to wait between each bleed tick
    bleed-tick-spacing: 15
    # The amount of bleed ticks to give
    bleed-ticks: 4
  seamless_movement:
    # The chance to ignore fall damage, as a percentage
    chance-per-level: 2
  potionmaster:
    # The percent more time for potions to last for each level of the effect
    percent-more-per-level: 4
  shamanism:
    # The percent faster regen for each level of the effect
    percent-faster-per-level: 4
  craftsmanship:
    # 100% is double durability
    percent-less-per-level: 3
  second_chance:
    # Items will try to heal every time durability damage is taken below this level
    below-durability-check: 30
    # Chance per level as a percentage
    # This will follow a binomial distribution where the amount of trials is the durability check (30 by default, see above)
    # Since this chance will be called many times, it would be best to have this be low.
    chance-per-level: 0.1

damage-indicators:
  # Requires HolographicDisplays to be installed
  enabled: true
  format:
    normal: "&7%damage%"
    crit: "&f✧ <gradient:#f953c6>%damage%</gradient:#b91d73> &f✧"
  max-x-offset: 0.6
  max-y-offset: 0.6
  max-z-offset: 0.6