#
# EcoSkills
# by Auxilor
#

gui:
  rows: 6

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111101111"
      - "111111111"
      - "110000011"
      - "110010011"
      - "111111111"
      - "111101111"

  player-info:
    row: 1
    column: 5

    name: "&f%player%&f's &fStats:"
    lore:
      - "&f"
      - " %ecoskills_defense_name%&f %ecoskills_defense%"
      - " %ecoskills_strength_name%&f %ecoskills_strength%"
      - " %ecoskills_crit_chance_name%&f %ecoskills_crit_chance%%"
      - " %ecoskills_crit_damage_name%&f %ecoskills_crit_damage%"
      - " %ecoskills_speed_name%&f %ecoskills_speed%"
      - " %ecoskills_wisdom_name%&f %ecoskills_wisdom%"
      - " %ecoskills_ferocity_name%&f %ecoskills_ferocity%"

  close:
    material: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

  skill-icon:
    name: "&#ff00ae%skill% &d%level_numeral%"
    lore:
      - "&8&o%description%"
      - "&f"
      - "%skill_specific%"
      - "&f"
      - "&fProgress to next level:"
      - "&8» &e%percentage_progress%"
      - "&8» &e%current_xp%&8/&7%required_xp% &fXP"
      - "&f"
      - "&eClick to view Level Progression!"

level-gui:
  rows: 6

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"

  progression-slots:
    # To set the order of the pattern,
    # Use 1-9 and then a-z: a goes after 9.
    pattern:
      - "109ab0jkl"
      - "2080c0i0m"
      - "3070d0h0n"
      - "4560efg0o"
      - "00000000p"
      - "00000000q"

    # If the amount of the item should be the level
    level-as-amount: true

    prev-page:
      material: arrow
      name: "&fPrevious Page"
      location:
        row: 6
        column: 4

    next-page:
      material: arrow
      name: "&fNext Page"
      location:
        row: 6
        column: 6

    close:
      material: barrier
      name: "&cClose"
      location:
        row: 6
        column: 5

    unlocked:
      material: lime_stained_glass_pane
      name: "&a%skill% Level %level_numeral%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"
        - "&f"
        - "&aUNLOCKED"
    in-progress:
      material: yellow_stained_glass_pane
      name: "&e%skill% Level %level_numeral%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"
        - "&f"
        - "&fProgress:"
        - "&8» &e%percentage_progress%"
        - "&8» &e%current_xp%&8/&7%required_xp% &fXP"
    locked:
      material: red_stained_glass_pane
      name: "&c%skill% Level %level_numeral%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"

  close:
    material: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

  skill-icon:
    name: "&#ff00ae%skill% &d%level_numeral%"
    lore:
      - "&8&o%description%"
      - "&f"
      - "%skill_specific%"
      - "&f"
      - "&fProgress to next level:"
      - "&8» &e%percentage_progress%"
      - "&8» &e%current_xp%&8/&7%required_xp% &fXP"
      - "&f"
      - "&eClick to view Level Progression!"

skills:
  # Add more levels depending on the highest max level for all skills
  level-xp-requirements:
    - 50
    - 125
    - 200
    - 300
    - 500
    - 750
    - 1000
    - 1500
    - 2000
    - 3500
    - 5000
    - 7500
    - 10000
    - 15000
    - 20000
    - 30000
    - 50000
    - 75000
    - 100000
    - 200000
    - 300000
    - 400000
    - 500000
    - 600000
    - 700000
    - 800000
    - 900000
    - 1000000
    - 1100000
    - 1200000
    - 1300000
    - 1400000
    - 1500000
    - 1600000
    - 1700000
    - 1800000
    - 1900000
    - 2000000
    - 2100000
    - 2200000
    - 2300000
    - 2400000
    - 2500000
    - 2600000
    - 2750000
    - 2900000
    - 3100000
    - 3400000
    - 3700000
    - 4000000

  # Ways to tell the player about skill progress
  progress:
    action-bar:
      # If the action bar should be used
      enabled: true
      # The actionbar message that should be sent
      format: "&f%skill% &8| &9(%current_xp%/%required_xp%) &e+%gained_xp%"
    sound:
      # If a sound should be played
      enabled: true
      # The sound that should be played
      id: entity_experience_orb_pickup
      # Pitch between 0.5 and 2
      pitch: 2
      # The volume
      volume: 0.1

  # Ways to tell the player about levelling up
  level-up:
    message:
      level-as-numeral: true
      enabled: true
      message:
        - "&f"
        - " &#ff00aeYou levelled up &d%skill%&#ff00ae to &eLevel %level%&#ff00ae!"
        - "&f"
        - " &#ff00ae&lREWARDS:"
        - "%rewards%"
        - "&f"
    sound:
      # If a sound should be played
      enabled: true
      # The sound that should be played
      id: entity_player_levelup
      # Pitch between 0.5 and 2
      pitch: 0.8

stats:
  defense:
    # 100% halves the incoming damage
    percent-less-damage-per-level: 1
  strength:
    # 100% is double damage
    percent-more-damage-per-level: 1
  crit_chance:
    # Nothing happens above 100%, 200% is the same as it.
    chance-per-level: 1
  crit_damage:
    # The percent more damage to deal on crits for each level.
    percent-more-damage-per-level: 2
    # The amount more damage to deal on crits by default.
    base-percent-more: 50
  speed:
    # The percent more speed to give for the speed attribute (internal in the game)
    # for each level
    percent-faster-per-level: 1
  wisdom:
    # The percent more xp to gain from orbs for each level of the stat.
    percent-more-xp-gain: 1
  ferocity:
    # The percent chance to deal damage twice
    chance-per-level: 0.5

effects:
  bountiful_harvest:
    description: "&a%chance%%&8 to get &a%multiplier%x&8 drops from farming"

    # Chance is as a percentage; if the chance for a player is over 100 then it will always be double drops
    # with a chance to get triple drops. Same goes if above 200, but then it will always be triple with a chance
    # for quadruple.
    chance-per-level: 8
  versatile_tools:
    description: "&8Deal &a%percent_more%%&8 more damage with pickaxes"

    # The percent (%) more damage to deal with a pickaxe for each level of the effect.
    percent-more-per-level: 8
  eye_of_the_depths:
    description: "&a%chance%%&8 chance to get rare drops from fishing"

    # Chance is as a percentage.
    chance-per-level: 0.1
    # The rare loot items are listed below.
    # You can import drops from the following plugins:
    # EcoArmor, EcoItems, Talismans, StatTrackers, EcoWeapons, Reforges, Oraxen
    # You can also use vanilla items with their material
    # You can set enchantments on items with the following syntax:
    # <item> <enchantment:level> <enchantment:level> etc
    # For example, a reaper scythe with Razor 4 and Criticals 3 would be:
    # ecoweapons:reaper_scythe razor:4 criticals:3
    rare-loot-items:
      - enchanted_book confusion:1
      - enchanted_book confusion:2
      - netherite_ingot
      - ecoarmor:set_miner_helmet
      - ecoarmor:set_miner_chestplate
      - ecoarmor:set_miner_leggings
      - ecoarmor:set_miner_boots
      - reforges:dynamic
  serrated_strikes:
    description: "&a%chance%%&8 to make your opponent bleed"

    # Chance is as a percentage.
    chance-per-level: 2
    # The damage to deal for each 'bleed tick'
    bleed-tick-damage: 2
    # The amount of ticks to wait between each bleed tick
    bleed-tick-spacing: 15
    # The amount of bleed ticks to give
    bleed-ticks: 4
  seamless_movement:
    description: "&a%chance%%&8 to ignore fall damage"

    # The chance to ignore fall damage, as a percentage
    chance-per-level: 2
  potionmaster:
    description: "&8Brewed potions last &a%percent_more%%&8 longer"

    # The percent more time for potions to last for each level of the effect
    percent-more-per-level: 4

    # The lore to add to indicate a duration buff
    lore:
      - ""
      - "&fPotionmaster Buff:"
      - "&8» &f+&e%seconds%&f Seconds"
  shamanism:
    description: "&8Heal &a%percent_faster%%&8 faster"

    # The percent faster regen for each level of the effect
    percent-faster-per-level: 4
  craftsmanship:
    description: "&8Axes take &a%percent_less%%&8 less durability damage"

    # 100% is unbreakable
    percent-less-per-level: 2
  second_chance:
    description: "&8Items have a &a%chance%%&8 chance to instantly repair below &a30&8 durability"

    # Items will try to heal every time durability damage is taken below this level
    below-durability-check: 30
    # Chance per level as a percentage
    # This will follow a binomial distribution where the amount of trials is the durability check (30 by default, see above)
    # Since this chance will be called many times, it would be best to have this be low.
    chance-per-level: 0.1
  efficient_brewing:
    description: "&8Potions take &a%seconds_less%&8 less seconds to brew"

    # The ticks faster brewing time for each level (default is 400)
    ticks-less-per-level: 6
  mystic_resilience:
    description: "&a%chance%%&8 chance to ignore negative potion effects"

    # Chance per level as a percentage
    chance-per-level: 0.1
  satiation:
    description: "&8Lose &a%percent_less%%&8 less hunger"

    # 100% is no hunger
    percent-less-hunger-per-level: 2
  golden_yield:
    description: "&a%chance%%&8 chance to get &a5x&8 drops"

    # Chance as a percentage
    chance-per-level: 0.3

    # The amount more drops to give
    drop-multiplier: 5
  dodging:
    description: "&a%chance%%&8 chance to ignore incoming damage"

    # The chance to ignore damage, as a percentage
    chance-per-level: 0.5
  accelerated_escape:
    description: "&8Run &a%percent_faster%%&8 faster for &a1.5&8 seconds after taking damage"

    # The percent faster speed, as a percentage
    percent-faster-per-level: 4

    # The duration to go faster for, in ticks
    ticks: 30

damage-indicators:
  # Requires HolographicDisplays to be installed
  enabled: true
  format:
    normal: "&7%damage%"
    crit: "&f✧ <gradient:#f953c6>%damage%</gradient:#b91d73> &f✧"
  max-x-offset: 0.6
  max-y-offset: 0.6
  max-z-offset: 0.6