name: EcoSkills
version: ${projectVersion}
main: com.willfp.ecoskills.EcoSkillsPlugin
api-version: 1.16
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - PlaceholderAPI
softdepend:
  - HolographicDisplays
  - Essentials
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:1.5.21'
  - 'org.jetbrains.exposed:exposed-core:0.34.1'
  - 'org.jetbrains.exposed:exposed-dao:0.34.1'
  - 'org.jetbrains.exposed:exposed-jdbc:0.34.1'

commands:
  ecoskills:
    description: Base Command
    permission: ecoskills.command.ecoskills
  skills:
    aliases:
      - stats
      - skill
    description: Open the skills menu
    permission: ecoskills.command.skills

permissions:
  ecoskills.*:
    description: All ecoskills permissions
    default: op
    children:
      ecoskills.command.*: true
  ecoskills.command.*:
    description: All commands
    default: op
    children:
      ecoskills.command.reload: true
      ecoskills.command.ecoskills: true
      ecoskills.command.reset: true
      ecoskills.command.skills: true
      ecoskills.command.give: true
      ecoskills.command.top: true
      ecoskills.command.rank: true

  ecoskills.command.reload:
    description: Allows reloading the config
    default: op
  ecoskills.command.ecoskills:
    description: Allows the use of /ecoskills.
    default: true
  ecoskills.command.skills:
    description: Allows the use of /skills.
    default: true
  ecoskills.command.reset:
    description: Allows the use of /ecoskills reset.
    default: op
  ecoskills.command.top:
    description: Allows the use of /ecoskills top.
    default: true
  ecoskills.command.rank:
    description: Allows the use of /ecoskills rank.
    default: true
  ecoskills.command.give:
    description: Allows the use of /ecoskills give.
    default: op

  ecoskills.xpmultiplier.50percent:
    description: Gives the player 50% more skill experience
    default: false
  ecoskills.xpmultiplier.double:
    description: Gives the player 2x skill experience
    default: false
  ecoskills.xpmultiplier.triple:
    description: Gives the player 3x skill experience
    default: false
  ecoskills.xpmultiplier.quadruple:
    description: Gives the player 4x skill experience
    default: false
