name: EcoSkills
version: ${projectVersion}
main: com.willfp.ecoskills.EcoSkillsPlugin
api-version: 1.16
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.21

commands:
  ecoskills:
    description: Base Command
    permission: ecoskills.command.ecoskills
  skills:
    description: Open the skills menu
    permission: ecoskills.command.skills

permissions:
  ecoskills.*:
    description: All ecoskills permissions
    default: op
    children:
      ecoskills.command.*: true
  ecoskills.command.*:
    description: All commands
    default: op
    children:
      ecoskills.command.reload: true
      ecoskills.command.ecoskills: true
      ecoskills.command.reset: true
      ecoskills.command.skills: true

  ecoskills.command.reload:
    description: Allows reloading the config
    default: op
  ecoskills.command.ecoskills:
    description: Allows the use of /ecoskills.
    default: true
  ecoskills.command.skills:
    description: Allows the use of /skills.
    default: true
  ecoskills.command.reset:
    description: Allows the use of /ecoskills reset.
    default: op
